### ISSUE TITLE
Recommendataion of a similar project

### ISSUE THREAD

**Issue by jwwthu** [BNN-UPC/GNNPapersCommNets#3]
Dear sir, I am maintaining and updating a similar Github project for the collection of Graph-based Deep Learning for Communication Networks (https://github.com/jwwthu/GNN-Communication-Networks). I would really appreciate that you could add a link to it and help to spread the word. Thanks!

**Comment by jsuarezv** [comment]
Hello,
Thank you for informing this. That is indeed a very interesting project. Our list is intended to be short and show only relevant references on different types of communication networks. We will refer to your repo for those readers that may be interested in a more comprehensive list.

By the way, we have recently published a magazine paper in IEEE Network. Maybe you can add it to your repo:

J. Suárez-Varela, P. Almasan, M. Ferriol-Galmés, K. Rusek, F. Geyer, X. Cheng, X. Shi, S. Xiao, F. Scarselli, A. Cabellos-Aparicio, P. Barlet-Ros, "Graph Neural Networks for Communication Networks: Context, Use Cases and Opportunities", IEEE Network, 2022.
[[DOI](https://doi.org/10.1109/MNET.123.2100773)]

Best regards,
José
